### PR TITLE
Fixup ailing sync prop access

### PR DESCRIPTION
**Pull request by 3commascapital**
upgrades go version to 1.20 and fixes up oncevalue access

### CODE REVIEW

**Comment by 3commascapital** [comment]
when using as a dependency in a v1.20 based repo, the following error is encountered:
```
$ go test
# github.com/anacrolix/log [github.com/anacrolix/log.test]
./callers.go:27:28: undefined: sync.OnceValue
FAIL    github.com/anacrolix/log [build failed]
```

**Comment by tsynik** [comment]
@anacrolix I also vote for this. Sometimez we need go1.20 support, for example for windows 7 builds of torrserver

**Comment by anacrolix** [comment]
I made https://github.com/anacrolix/log/commit/dfa5cb14b878f075fd0a5bca9ba28bc55bd841c9 as an alternative, that uses sync.Once for versions previous to Go 1.21. This should be faster. The minimum version for anacrolix/log is now 1.19 instead of 1.21. There is another small change that could be made to support versions prior to 1.19, but I will only make it if it's needed. Could you let me know how https://github.com/anacrolix/log/commit/dfa5cb14b878f075fd0a5bca9ba28bc55bd841c9 goes for you? Use `go get github.com/anacrolix/log@backwards-compat`.

**Comment by tsynik** [comment]
> Could you let me know how [dfa5cb1](https://github.com/anacrolix/log/commit/dfa5cb14b878f075fd0a5bca9ba28bc55bd841c9) goes for you? Use `go get github.com/anacrolix/log@backwards-compat`.

there is no compile errors with dfa5cb1 and go1.20.13. thanks for the fix

**Comment by anacrolix** [comment]
Fixed in `v0.15.0`. Thanks very much!

**Pull request closed without merging**
